FROM node:20-alpine as build

WORKDIR /app/frontend

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ ./

RUN npm run build

FROM node:20-alpine

WORKDIR /app/frontend

COPY frontend/package*.json ./

RUN npm install

COPY --from=build /app/frontend/dist ./dist

ENV NODE_ENV=production
ENV PORT=5174

EXPOSE 5174

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0"]
